### ISSUE TITLE
can't be installed through go install && no github releases for linux/osx

### ISSUE THREAD

**Issue by pathcl** [Envoy49/go-spotify-cli#14]
First of all; thanks! I was looking for a cli tool around spotify.

I just tried to install it but.. 

```
pathcl@tallarin ~ % go install github.com/envoy49/go-spotify-cli@v1.0.41
go: github.com/envoy49/go-spotify-cli@v1.0.41: module github.com/envoy49/go-spotify-cli@v1.0.41 found, but does not contain package github.com/envoy49/go-spotify-cli
```

I find very useful to install cli tools this way. Also I noticed releases for `darwin`, `linux` are not available here: https://github.com/Envoy49/go-spotify-cli/releases/tag/v1.0.41.

Would it make sense to fix it? I can work on it.

**Comment by Envoy49** [comment]
Hi @pathcl , let me try to automate it quickly and see results of build.
Sorry I haven't foreseen these scenarios.

**Comment by Envoy49** [comment]
Hey, all good now.
Can you please test it?

**Comment by Envoy49** [comment]
I think with this approach I can get rid of Homebrew and Winget installation processes? What do you think @pathcl ?

**Comment by pathcl** [comment]
@Envoy49 honestly I find brew really annoying sometimes. This approach is way cleaner I'd say. Now it's working!

```
pathcl@tallarin ~ % go install github.com/envoy49/go-spotify-cli@latest
go: downloading github.com/envoy49/go-spotify-cli v1.0.48
go: downloading github.com/sirupsen/logrus v1.9.3
go: downloading github.com/charmbracelet/lipgloss v0.8.0
go: downloading github.com/manifoldco/promptui v0.9.0
go: downloading github.com/spf13/cobra v1.7.0
go: downloading github.com/briandowns/spinner v1.23.0
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/pkg/browser v0.0.0-20210911075715-681adbf594b8
go: downloading golang.org/x/sys v0.13.0
go: downloading github.com/mattn/go-runewidth v0.0.15
go: downloading github.com/muesli/reflow v0.3.0
go: downloading github.com/muesli/termenv v0.15.2
go: downloading github.com/chzyer/readline v0.0.0-20180603132655-2972be24d48e
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/fatih/color v1.7.0
go: downloading github.com/mattn/go-isatty v0.0.19
go: downloading golang.org/x/term v0.1.0
go: downloading github.com/rivo/uniseg v0.4.4
go: downloading github.com/mattn/go-colorable v0.1.2
go: downloading github.com/aymanbagabas/go-osc52/v2 v2.0.1
go: downloading github.com/lucasb-eyer/go-colorful v1.2.0

pathcl@tallarin ~ % cd go/bin

pathcl@tallarin bin % ll
total 111776
-rwxr-xr-x@ 1 pathcl  staff  12928802 Jan  4 11:19 go-spotify-cli
```

I noticed two more things:

- we don't have a way to tell which version we're running. If you type go-spotify-cli there's no version command or git hash detailed.
- There's no support for arm64 yet on [releases](https://github.com/Envoy49/go-spotify-cli/releases/tag/v1.0.48). You could use goreleaser as a github action or something like [this](https://blog.devgenius.io/goreleaser-build-multi-arch-docker-images-8dd9a7903675)

**Comment by Envoy49** [comment]
let me update the readme for this approach and get rid of the homebrew release steps and forget about Winget haha

This one I noticed as well

`we don't have a way to tell which version we're running. If you type go-spotify-cli there's no version command or git hash detailed.`

I will create an issue for that and try to add it soon.

Also can you please elaborate more on this?

`There's no support for arm64 yet.`

**Comment by Envoy49** [comment]
Got the readme updated
