### ISSUE TITLE
Doc: the go install command does not work

### ISSUE THREAD

**Issue by christophberger** [Envoy49/go-spotify-cli#19]
The `go install` command in the README is hard-coded to install v1.0.0 and fails:

```
> go install github.com/envoy49/go-spotify-cli@v1.0.0
go: downloading github.com/envoy49/go-spotify-cli v1.0.0
go: github.com/envoy49/go-spotify-cli@v1.0.0: module github.com/envoy49/go-spotify-cli@v1.0.0 found, but does not contain package github.com/envoy49/go-spotify-cli
```

(Using `go install github.com/envoy49/go-spotify-cli@latest` works.)

**Comment by Envoy49** [comment]
This is what README says at the moment

<img width="908" alt="image" src="https://github.com/Envoy49/go-spotify-cli/assets/94023356/b9ee7fb5-a5c6-43d7-98e0-8a6aed0e92bb">

`go install github.com/envoy49/go-spotify-cli@v1.0.0` is just an example.
Current version needs to be used.

I will update README so people don't get confused.
