### ISSUE TITLE
go install vs packet managers

### ISSUE THREAD

**Issue by christophberger** [Envoy49/go-spotify-cli#20]
The readme says,

"Previous installation methods using Homebrew and Winget have been phased out in favor of the more direct go install method."

While `go install` may be "more direct" by some definition, it has two severe drawbacks:

1. `go install` prefers Go developers over people who don't want to install Go or don't want to be bothered with doing developer-level things just for installing an app.
2. `go install` has no auto-update functionality.

To reach a wider audience, you might want to give [goreleaser](https://goreleaser.com) a try. Goreleaser makes generating installation packages trivial for several package managers, and manageable for several more. (I [tried it myself](https://appliedgo.net/release/) and am pleased with the result.)

**Comment by Envoy49** [comment]
Incorporating goreleaser into the release process will require some time and effort. My initial experience with goreleaser, during my first attempts at distributing this package, was not particularly smooth. However, I acknowledge its importance and benefits. Meanwhile I can add Homebrew and Winget installation methods back to the README. Given the frequent mentions and recommendations for goreleaser, I plan to revisit and continue my previous work with it to improve distribution strategy.

**Comment by Envoy49** [comment]
Homebrew and Winget installation options are added back in README.
Goreleaser will be considered in future.
