### ISSUE TITLE
Error: No devices available. Please activate at least one device.

### ISSUE THREAD

**Issue by christophberger** [Envoy49/go-spotify-cli#21]
After creating an app on Spotify and successfully receiving the token and secret (verified in .yaml), I get an error when trying to play a track or list the devices. 

The README does not tell how to activate a device. 

```sh
> go-spotify-cli device
No devices available. Please activate at least one device.
> go-spotify-cli play
No devices available. Please activate at least one device.
```

The official Spotify GUI client works fine on my machine. (macOS Sonoma)

**Comment by Envoy49** [comment]
Thanks for the feedback @christophberger .
This error means that no device is available for spotify to play any track, where ClientId and ClientSecret used to execute any command doesn't have any GUI to communicate with.
I believe the error message should be improved in this case but that is not an issue in this case 
Could you please verify that it is indeed the correct account.
Also it can be verified on mobile phone for example.
I tested this functionality many times and had this error message only when the GUI Application was completely closed, which means that it has to be manually opened.

**Comment by Envoy49** [comment]
This issue will be closed within one week after inactivity.

**Comment by Yuunora** [comment]
@Envoy49  Add an additional step in the configuration menu "Start the Spotify app on the device on your choice" to make it more straightforward.

**Comment by christophberger** [comment]
> Could you please verify that it is indeed the correct account.

This. For some reason, I was logged into an old Spotify developer account that had nothing to do with my Spotify user account. 

After fixing this, I see my computer as a playback device. Thanks for reminding me to double-check the account.
